### ISSUE TITLE
useTransition not transition item to correct position when put pages array in Component.

### ISSUE THREAD

**Issue by yuwanlin** [react-spring/react-spring#669] opened 2019-05-11 01:04 UTC
## 🐛 Bug Report

useTransition not transition item to correct position when put pages array in Component.

## To Reproduce

here is the bug codesanbox: https://codesandbox.io/s/qz03y031rw
click prev/next button, next page will transition to incorrect position.

this codesanbox is fork from https://codesandbox.io/embed/1y3yyqpq7q，but only move pages into Component. This is because pages data will be produced from network. 

## Expected behavior
click prev/next button, next page will transition to incorrect position.

**Comment by drcmda** [comment] 2019-05-16 06:51
not sure what exactly the problem is, it does behave weird. i do believe that fishing the direction from state directly will fail, because these functions (enter/leave) are called asynchroneously. i've made something like this a while ago: https://codesandbox.io/s/94yjvql35y

**Comment by devarsh** [comment] 2019-06-01 10:25
So I've created a simple Authentication component, it has 3 child components for username, password and Otp(2fa), and all these child components have a header and Body component, these components are navigated using `react-router`, the header component is navigated without animation but the body is animated using React-spring `useTransition` and there is additional logic to handle directional transition when clicking browser back and forward button

Body component of pages animates during navigates which is intended, but for some reason when I added the 3rd child component i.e (2fa) the header component animated during navigation and not the Body component of the page, it is strange maybe I'm using react-spring `useTransition` and react-router wrongly, but I've checked everything and for some reason i can't understand whats going on.

I've been stuck at this and drawing blank as to why this is happening. Any help would be greatly appreciated.

Below is the codesandbox link, while running the demo click the next button and also use browser back and forth button.

https://codesandbox.io/embed/myapp-os3fc

**Comment by aleclarson** [comment] 2019-06-09 22:41
Fixed in v9.0.0-beta

**Closed by aleclarson** 2019-06-09 22:41 UTC
Labels: bug

**Comment by yuwanlin** [comment] 2019-08-17 02:46
> Fixed in v9.0.0-beta

yeah, thank you. when v9.0.0 version will be released ?

**Comment by aleclarson** [comment] 2019-08-17 03:28
@yuwanlin 	Before the end of the year, probably. You can use it today, just pin the version instead of using caret ranges.

**Comment by yuwanlin** [comment] 2019-08-17 06:49
@aleclarson got it. thanks.
