### ISSUE TITLE
Nextjs 9 & react-spring 9: useSpring opposite values in prod/dev-mode

### ISSUE THREAD

**Issue by secretlifeof** [react-spring/react-spring#804] opened 2019-09-05 15:36 UTC
## 🐛 Bug Report

We are using Nextjs 9 & React-spring 9-beta.34. De problem we are experiencing while using useSpring is that transform reacts differently depending on Nextjs build mode prod vs dev. Visibility behaves correctly, maybe because it is a Boolean value. So in development it is correct. Probably related to #778.

To be more clear. When projectDetailVisibility == true: 
  In production = 'translate3d(0, 0vh, 0)'
  In development = 'translate3d(0, 100vh, 0)'

```
const styleProps = useSpring({
    to: async (next) => {
         await next({
		visibility: projectDetailVisibility ? 'visible' : 'hidden'
	});
	await next({ transform: projectDetailVisibility ? 'translate3d(0, 100vh, 0)' : 'translate3d(0, 0vh, 0)' });
    },
    from: { visibility: 'visible', transform: 'translate3d(0, 100vh, 0)' }
});
```

## To Reproduce

If it is important to build a codeSandbox, please ask me :) 

## Expected behavior

I expect useSpring to behave the same in production and development.

In React-spring v8.0.27 it works correctly.

## Environment

- `react-spring` v9.0.0-beta.34
- `react` v16.9.0
- `next` v9.0.6-canary.0 (Have tried different builds)

**Comment by aleclarson** [comment] 2019-09-05 21:02
Please provide a CodeSandbox or git repo. Thanks! 👍

**Comment by secretlifeof** [comment] 2019-09-09 12:01
Yes sure!

Codesandbox:
https://codesandbox.io/embed/github/secretlifeof/react-overlay-images-react-spring-bug/tree/master/?fontsize=14

Github repo:
https://github.com/secretlifeof/react-overlay-images-react-spring-bug

In the codesandbox everything seems to work. To view the false behaviour please:

```
clone GitHub repo
yarn
yarn build
yarn start
```

**Comment by XeeD** [comment] 2019-09-16 10:40
After trying out v9 of `react-spring` we are suffering the same issue. Most of the animations work just fine, but for some simple `useSpring` based animation are running in the opposite direction when we enable the production mode.

Or app is not based on Next.js but on Create React App (generated a couple of weeks ago).

```js
const InlineLabel = ({
  fieldIsFocused,
  fieldHasValue,
  children,
}) => {
  const labelProps = useSpring({
    transform:
      fieldIsFocused || fieldHasValue
        ? 'scale(0.8) translate3d(0px, -12px, 0px)'
        : 'scale(1) translate3d(0px, 0px, 0px)',
  });

  return (
    <animated.label
      hasError={fieldHasError}
      style={labelProps}
    >
      {children}
    </animated.label>
  );
};
```

If it helps I can try to put the whole example into a repo.

**Comment by lettertwo** [comment] 2019-12-13 04:32
FWIW, I've seen this same thing in a production Gatsby build using `react-spring@9.0.0-beta.34` alongside `styled-components`. I haven't figured out why this happens in production, but i've managed to reproduce the bug reliably with a relatively simple CRA setup:

https://codesandbox.io/s/zealous-visvesvaraya-iw6qj

(**NOTE:** The issue only seems to manifest in production builds, so the codesandbox preview should appear to work as intended!)

To see the bug, view that same example built for production:

https://csb-iw6qj.netlify.com/

- In this repro, the combination of `react-spring@9.0.0-beta.34` and `styled-components` reliably reproduces the issue in production
- Upgrading `react-spring@9.0.0-canary.809.5.f01ecc2` resolves the issue in this repro

**Comment by aleclarson** [comment] 2019-12-13 05:06
@lettertwo That's not [the latest](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404) canary version. LMK if `
9.0.0-canary.808.12.11b2708` works or not.

**Comment by lettertwo** [comment] 2019-12-13 15:25
@aleclarson woops, i grabbed the first one in the list yarn showed me! I switched to `9.0.0-canary.808.12.11b2708` and can confirm it works.

I would love to know what the underlying issue was, if you have insight and care to share!

**Comment by edwardyh80** [comment] 2020-01-16 08:46
I could confirm this problem from CRA as well. Any fix?

**Comment by aleclarson** [comment] 2020-01-16 14:16
@samselikoff The v9 canary has a new API for `useTransition`. See [here](https://github.com/react-spring/react-spring/pull/809).

@edwardyh80 Please try the [latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404).

**Comment by edwardyh80** [comment] 2020-01-17 00:28
Just realized the version I had was beta...canary build solved this problem. Looking forward to official release of v9.

**Comment by aleclarson** [comment] 2020-05-09 14:12
Closing this according to reports of it being fixed by the canary.

If you see this issue, please try with the latest version (`9.0.0-rc.2` currently, #985).

**Closed by aleclarson** 2020-05-09 14:12 UTC
Labels: bug, v9
