### ISSUE TITLE
Trouble using {config: (key) => ...} with useTrail

### ISSUE THREAD

**Issue by cwgw** [react-spring/react-spring#590] opened 2019-03-12 00:45 UTC
When I set `config` as a function in `useTrail`, it doesn't get called with the arguments I'd expect.

I'd love to be able to do something like below with `useTrail`, but currently the `key` parameter I get is not a reference to the animated value; rather, it's a reference to each spring's index in the set.

```
const trail = useTrail(items.length, {
  to: {
    opacity: 0,
    translateY: 50,
  },
  config: (key) => ({
    clamp: key === 'opacity'
    ...
``` 

Rather than getting `opacity` and `translateY`, I'm getting `0`, `1`, `2`, etc. I imagine this might be by design, but it'd be great to get both the key and index.

I love this library by the way. Thank you for all of the great work!

**Comment by Mathspy** [comment] 2019-03-12 02:30
_Disclaimer: I am also new to this so everything ahead might be completely incorrect_
This is by design, I think, as having multiple configurations is basically having multiple different "springs". The idiomatic way of doing this would be using several `useTrail`s, each with a different property (one for opacity, one for translateY). If there are a lot of duplicate settings you can extract those to an object that you spread

The `key => config` functionality is used when you want each individual item of your trail to have a different configuration

**Comment by aleclarson** [comment] 2019-04-01 02:37
The `config` function is called `items.length` times. It lets you customize each spring individually, as @Mathspy said. It would be easier to help you if you provided a CodeSandbox. Closing for now.

**Closed by aleclarson** 2019-04-01 02:37 UTC
Labels: question

**Comment by sjnonweb** [comment] 2019-04-29 14:36
I noticed a regression with `useTrail` in this release, so when the number of items is 0 then i get an error saying `Cannot read props of undefined`.

I'll try to create a repro when i get the time.

code snippet:
```
const data = [];
const trails = useTrail(data.length, {
  config: config.stiff,
  from: {
    rotate: -90
  },
  rotate: 0,
});
```

**Comment by aleclarson** [comment] 2019-04-29 14:37
@sjnonweb If you're talking about the v9 beta, please open a new issue. Thanks!

**Comment by sjnonweb** [comment] 2019-04-29 14:42
Yes i commented here by mistake, i have posted my comment here:
https://github.com/react-spring/react-spring/issues/642#issuecomment-487606053
