### ISSUE TITLE
Testing disappearance with useTransition doesn't work

### ISSUE THREAD

**Issue by SKHecht** [react-spring/react-spring#1148] opened 2020-09-15 15:44 UTC
## 🐛 Bug Report

I'm using `useTransition` to remove a component from my app, and would like to test this behavior, however I cannot get the component to actually be removed from the page. I've tried using both enzyme and the React Testing Library. 

## To Reproduce

```
import { render, act, fireEvent, waitForElementToBeRemoved } from '@testing-library/react';
import { mount } from 'enzyme';
import { useTransition, animated } from 'react-spring';

const MyComponent = () => {
    const [visible, setVisible] = React.useState(true);
    const transitions = useTransition(visible, null, {
        from: { transform: 'translateY(0%)' },
        leave: { transform: 'translateY(-100%)' },
    });
    return transitions.map(({ item, key, props}) => item && (
        <animated.div key={key} style={props}>
            <div onClick={() => setVisible(false)}>
                Hello world
            </div>
        </animated.div>
    ));
};

describe('My Component', () => {
    it('disappears (RTL)', async () => {
        jest.useFakeTimers();

        const { getByText } = render(<MyComponent />);
        fireEvent.click(getByText('Hello world'));
        await act(async () => jest.runAllTimers());

        expect(getByText('Hello world')).not.toBeInTheDocument();
    });
    it('disappears (enzyme)', async () => {
        jest.useFakeTimers();

        const wrapper = mount(<MyComponent />);
        wrapper.find('div').at(1).simulate('click');
        await act(async () => jest.runAllTimers());
        wrapper.update();

        expect(wrapper.isEmptyRender()).toBeTruthy();
    });
});
```

Both tests fail on the `expect`. I've also tried using RTL's [waitForElementToBeRemoved](https://testing-library.com/docs/guide-disappearance#waiting-for-disappearance) utility, and it times out without the component being removed.

## Link to repro (highly encouraged)

https://codesandbox.io/s/determined-smoke-ickw5

The tests are there as well, however, due to https://github.com/codesandbox/codesandbox-client/issues/4887, you can't actually run them. Furthermore, `jest.useFakeTimers` is also not supported in codesandbox currently https://github.com/codesandbox/codesandbox-client/issues/513

I'm still including them so someone could copy them if they'd like.

## Environment

- `react-spring` v8.0.27, also tried v9.0.0-beta.34
- `react` v16.8.6
- `jest` v24.9.0
- `@testing-library/react` v9.4.0
- `enzyme` v3.11.0

**Comment by aleclarson** [comment] 2020-09-15 18:26
Duplicate of #1048

**Closed by aleclarson** 2020-09-15 18:26 UTC

**Comment by SKHecht** [comment] 2020-09-15 19:29
@aleclarson #1048 is certainly similar in nature to my ticket, but it doesn't actually help me to resolve the issue at hand. I tried adding
```
Globals.assign({ skipAnimation: true })
```
as per that issue. I also tried 
```
mockRaf = createMockRaf()
Globals.assign({
       now: mockRaf.now,
       performanceNow: mockRaf.now,
       requestAnimationFrame: mockRaf.raf,
       cancelAnimationFrame: mockRaf.cancel,
       frameLoop: new FrameLoop(),
});
// in test
... click component ...
mockRaf.flush();
await waitForElementToBeRemoved(() => ...);
```
as per https://github.com/react-spring/mock-raf. I tried with and without `jest.useFakeTimers()`.

Nothing has been able to actually remove the component during the test. Perhaps I should have filed this as a question, the question being "How to test disappearance with useTransition". Or perhaps the bug should have been the distinct lack of documentation on how to test usages of the hook.

It's not particularly clear how the writer of #1048 got their tests working.

**Comment by aleclarson** [comment] 2020-09-15 19:40
In my opinion, you're wasting your time testing DOM removal by `useTransition`, because that's already verified by `react-spring` tests (at least in v9, not sure if v8 has any tests like that).

**Comment by SKHecht** [comment] 2020-09-15 19:46
I'm not trying to test `useTransition`'s behavior; I'm testing the behavior of the click handler in my component. I suppose I could mock out `useTransition`, but that would take a nontrivial amount of work so I was hoping to be able to just more straightforwardly simulate the user clicking the component and causing it to disappear (after the animation).

**Comment by rovolution** [comment] 2022-08-11 18:03
I am experiencing the same problem

**Comment by rovolution** [comment] 2022-08-11 18:03
@SKHecht did you ever get a workaround or solution for this? thanks!!

**Comment by rovolution** [comment] 2022-08-11 18:21
> In my opinion, you're wasting your time testing DOM removal by useTransition, because that's already verified by react-spring tests (at least in v9, not sure if v8 has any tests like that).

Would respectfully disagree with this @aleclarson. There could be application logic that may involves removing elements from a list (for ex: client-side filtering a list of results) and you want to have test coverage around making sure this behavior works as expected.

**Comment by joshuaellis** [comment] 2022-08-15 07:44
Hey @rovolution, Alec doesn't work on react-spring anymore. But if you're wanting to re-open this, why not make a new discussion with the issue you're facing etc.? We can discuss it better there with more visibility.
