### ISSUE TITLE
Need a solution to set transform to none in order to make child's position fixed works

### ISSUE THREAD

**Issue by zhaoyinji** [react-spring/react-spring#1132] opened 2020-09-04 12:00 UTC
## 🚀 Feature Proposal
Need a solution so when the animation is finished, we can set transform to none.

## Motivation
Currently, the child's fixed position won't work properly when the parent has the transform style.

## Example
I have tried the hack way to set the transform to none, then the old animation of enter and leave will be overridden because of immediate: true
```
enter={[
  {
      opacity: 1,
      transform: 'translate3d(0%,0,0)',
   },
   { transform: 'none', immediate: true }
]}
leave={[
   { transform: 'translate3d(0%,0,0)', immediate: true },
   {
       opacity: 0,
       transform:  'translate3d(100%,0,0)',
    }
]}
```

**Comment by aleclarson** [comment] 2020-09-04 16:21
Duplicate of #747

**Closed by aleclarson** 2020-09-04 16:21 UTC
Labels: enhancement

**Comment by zhaoyinji** [comment] 2020-09-05 20:40
@aleclarson Thank you for the fast response. 

I have read through the case #747 several times before opening this case. I don't quite understand the solution for fixed postion problem in the 9rc2. Could you please enlighten me?
