### ISSUE TITLE
infinite loop (freeze) when setState is called

### ISSUE THREAD

**Issue by cztomsik** [react-spring/react-spring#930] opened 2020-02-08 16:59 UTC
## 🐛 Bug Report
This is really weird and I'm not sure if it's a bug or just wrong example but I think it should work because `await` should be resolved in the next tick but it doesn't seem to be.

## To Reproduce
- `useSpring()` with infinite promise generating new spring state (just like the one from examples)
- add extra `useState()`
- call that `setState` during `onClick`

## Expected behavior
I think it should not cause infinite loop (I'd understand if it kept spinning but it freezes other 

## Link to repro (highly encouraged)
https://codesandbox.io/s/practical-mountain-ps9sc

![image](https://user-images.githubusercontent.com/3526922/74088836-e3790680-4a9a-11ea-844a-2f33c30846c1.png)

## Additional context
I've tried this outside of code-sandbox and for some reason, no other event loop callback gets called (it will **freeze the window**), it's almost like if some V8 optimization kicked in and suddenly turned async iteration into a sync one. But it happens in Firefox too so I'm really not sure what's going on here.

You can test this easily with setInterval(() => console.log('tick'), 1000) but you need to do it locally, without codesandbox checks.

## Environment
- `react-spring` v8.x.x
- `react` v16.8.x

**Comment by aleclarson** [comment] 2020-02-08 17:19
Seems like a duplicate of #591

Please try with v9:

```
npm install react-spring@next
```

**Closed by aleclarson** 2020-02-08 17:19 UTC
Labels: bug

**Comment by cztomsik** [comment] 2020-02-08 19:09
works, thx
