### ISSUE TITLE
Feature Request: Typescript Support

### ISSUE THREAD

**Issue by thupi** [react-spring/react-spring#26] opened 2018-04-12 22:35 UTC
Hi,

This is kind of ground breaking. I think this is er very easy and well thought abstraction for animating stuff based on state. I will definitely take a closer look into this tool :-) 

My biggest problem(which is kind of small) at the moment is that there aren't any typings to find for this package yet. I would really love to see some typings for this libary as it would make the whole API easier to get into and make it way easier to use in Typescript projects :-)

**Comment by thupi** [comment] 2018-04-12 22:38
I have a hard time finding time to write a good and complete type definition for this project soon but i will definitely let you know if or when i have the time to go through the type definition :-)

**Comment by drcmda** [comment] 2018-04-13 09:31
I welcome PRs. I have little experience in TS myself and found it hard to wrap my head around. If you find the time to create typings, that would be awesome. 😀

**Comment by Cryrivers** [comment] 2018-04-18 06:32
I'm currently evaluating the transition from `react-motion` to `react-spring` in our products, might have time to make the type definition.

**Comment by nelsliu9121** [comment] 2018-04-26 03:01
Should this issue be reopened? Due to the fact that the typing is only half finished, and ts compiler will scream when you use components other than `Spring`.

**Comment by drcmda** [comment] 2018-04-26 06:19
Sure.

**Comment by radudascaluntt** [comment] 2018-05-08 21:35
Hey everyone,

I've tried to add the missing types. I'm relatively new to TypeScript so I'm sure I did something wrong. Basically I was just copy & pasting the stuff that I have found in the initial `index.d.ts` file.

It would be great if I can get some advice/help on how to test the annotations before I do a pull request.

**Comment by Cryrivers** [comment] 2018-05-09 06:39
@radudascaluntt no worries, you can just create a PR!

**Comment by radudascaluntt** [comment] 2018-05-09 07:42
Will make the PR from another account. I forgot I was using this one yesterday :)

**Comment by crimx** [comment] 2018-05-12 17:16
Hi @radudascaluntt I wrote the current `Spring` typing. Didn't write others because I haven't got a change to use them yet.

You can use `tsc` or vscode to test the syntax. It's a bit hard to test integration because the project itself doesn't have testing yet.

I first edited the `index.d.ts` directly within my own project to make sure it worked. And then eyeballed the source for places I wasn't quite sure about.

Most of the time you just need to follow the `propTypes`.

Hope this helps.

**Comment by swashata** [comment] 2018-05-25 12:03
For the time being I've found that adding the path to `jsconfig.js` file makes vscode provide some intellisense

```js
{
  "paths": {
  // ...
    "react-spring": ["./node_modules/react-spring/src/index.js"], // Not ready yet
  },
  // ...
}
```

**Comment by drcmda** [comment] 2018-05-28 11:26
@raspo could you make a PR and add it to the build? TS support is supper spotty it seems and the current PRs have all fallen asleep.

**Comment by ticruz38** [comment] 2018-06-04 10:01
Providing only the Spring component in typings.d.ts is not a good idea.
VSCode then thinks the library does have a typings file (which is incomplete) and trigger errors when importing any other component such as Transition.
Either update the typings or remove it completely.

**Comment by jariz** [comment] 2018-06-05 11:57
@drcmda I would just merge #84, it probably still misses some things, but it's better than having typings for only 1 out of 5 components, which is the state we're in now.

**Comment by drcmda** [comment] 2018-06-05 12:14
@jariz thanks, very happy about getting help here - i'll merge it

**Comment by simonbuchan** [comment] 2018-06-11 00:55
I've been working on filling out typings for this, but I've ran into an issue where typescript stops being able to infer the render argument type as soon as `native` is supported. Simplifying:

```ts
declare class AnimatedValue<T> {
  interpolate<U>(map: (value: T) => U): AnimatedValue<U>;
}

type AnimatedValueMap<T> = { [N in keyof T]: AnimatedValue<T[N]>; };

declare const animated: // distractingly big, maps JSX.IntrinsicElements to ComponentType<> with props that take AnimatedValue

type RenderPropsBase<T> = {
  render: (value: T) => React.ReactNode;
}; // | { children: ... }, etc...

type RenderProps<T> =
  | RenderPropsBase<T> & { native?: false }
  | RenderPropsBase<AnimatedValueMap<T>> & { native: true }
  ;

type TransitionProps<T> = RenderProps<T> & { from?: T; enter?: T; leave?: T; };

declare class Transition<T> extends React.PureComponent<TransitionProps<T>> { }

const dynamicRenderElement = (
  <Transition
    from={{ x: 0 }}
    enter={{ x: 100 }}
    render={props => ( // Parameter 'props' implicitly has an 'any' type.
      <div
        style={{ left: props.x }}
      />
    )}
  />
)

const nativeRenderElement = (
  <Transition
    native
    from={{ x: 0 }}
    enter={{ x: 100 }}
    render={props => ( // Parameter 'props' implicitly has an 'any' type.
      <animated.div
        style={props.x.interpolate(left => ({ left }))}
      />
    )}
  />
)
```

If either option in `RenderProps<T>` is commented out, the other one works with full inference, so this is pretty annoying, otherwise you have to annotate the props types on both sides as `: { x: number }` or `: { x : AnimatedValue<number> }` (or in general, `: T` and `: AnimatedValueMap<T>`).

The existing typings seem to "solve" this by removing any type association between the provided values (`from`, `enter`) and the `render` / `children` argument, meaning you don't have any type checking on the values, or inference on the args, but I haven't double-checked this.

I'll keep poking at this, but would it make sense from the JS side to offer, e.g. `<native.Transition />` as a friendlier to typescript option to `<Transition native />`?

**Comment by drcmda** [comment] 2018-06-11 07:57
@simonbuchan i see, but is there no other way? Can't props be simply either an object of values and strings or an object of animatedValues? This would cause some confusion otherwise. I wanted the api to stay simple, where "native" wouldn't be that different from the default. 

PS. you only need to interpolate values if you change their structure:

```jsx
render={props => (
  <animated.div style={{ left: props.x }} />
)}
```

**Comment by drcmda** [comment] 2018-06-11 08:32
Yeah 😱Does TS run in CodeSandBox? If we re-create your snippet above to demonstrate and isolate the problem, maybe it helps showing it around to get some input. 

If nothing helps we could make a typescript target with forward components, it would be easy to define, the build chain is already equipped for it.

**Comment by simonbuchan** [comment] 2018-06-11 09:02
Since it's just a typing issue, the standard is the [playground](http://www.typescriptlang.org/play/) for repro issues, e.g. a TS bug report, but I would like to reduce it a bit more first.

What I've got so far now implies that TS doesn't know how to contextually type the JSX props from the component signature, and it works without the union since the non-contextual inference still works, but that doesn't seem to make sense with the parameter being contextually typed. 😵

I could throw up what I've got tomorrow (9:00 PM here 😉) for this side, though, if anyone wants to give it a stab.

**Comment by kuuup-at-work** [comment] 2018-06-12 07:06
@simonbuchan 

> Nope, then you can't use props.foo.interpolate(), because props.foo might be number instead of AnimatedValue<number>, and you can't assign props.x to left, because animated.div's left is AnimatedValue<number> and props.x might be a number, and vice-versa for non-animated div.

You must check `props.foo` with `typeof` during runtime and then cast it to `number` or `AnimatedValue<number>`.

**Comment by simonbuchan** [comment] 2018-06-12 07:16
No that's not needed if you have the union at a higher lever and have something that can distinguish, e.g. here you can detect based on whether `native` is provided which will be passed.

E.g. the following works properly in typescript:

```ts
declare class AnimatedValue<T> {
    interpolate<U>(map: (value: T) => U): AnimatedValue<U>;
}

type DynamicProps<T> = { native: false, value: T, render: (value: T) => string };
type NativeProps<T> = { native: true, value: T, render: (value: AnimatedValue<T>) => AnimatedValue<string> };
type AutoProps<T> = DynamicProps<T> | NativeProps<T>;

declare function renderAuto<T>(props: AutoProps<T>): string;

renderAuto({
    native: false,
    value: 123,
    render: x => x.toFixed()
});
renderAuto({
    native: true,
    value: 123,
    render: ax => ax.interpolate(x => x.toFixed())
});
```

Interestingly, you can't make `native` optional there, even though it should know it has to be `DynamicProps<native>`. since there's no `native` property, which might be related.

**Comment by drcmda** [comment] 2018-06-12 10:30
@simonbuchan i'm a total beginner when it comes to TS, but does that mean it can be solved without having to duplicate all primitives (NativeSpring, etc.) ?

**Comment by simonbuchan** [comment] 2018-06-12 11:04
I mean, what I've got will work fine so long as you provide the type for the render argument, the win over the current types being that it can check if the values are compatible - but that's not really up to my expectations (you shouldn't have to read docs on how to use the typings for a library). Typescript already has all the information to infer everything itself, and can figure out similar, but simpler cases like in the example above, so I think this is either just a bug, or an improvement to TS they would be happy to add.

The suggestion for `<native.Foo>` would mean it wouldn't have to wait for that, though, (and I kind of like the symmetry with `<animated.foo>`), but you should in general only be changing libraries to fit typescript if it actually makes the library better even without types, which this isn't clearly so - one reason you might break the native types out for is if it means dead code elimination works better, for example?

**Comment by drcmda** [comment] 2018-06-12 12:15
The additional payload for native and animated.element isn't that big. If size is really an issue there would be more efficient ways, for instance react-spring/dist/universal (doesn't contain native, no colors) or react-spring-numerical (can be native, but no interpolations, just numbers => 2kb).

**Comment by vanthiyathevan** [comment] 2018-06-15 14:00
I see that in `TransitionProps`, `keys` property is not marked as optional even though the comment says it can be ommited if children/render aren't array.

**Comment by mfarhadpur** [comment] 2018-06-18 07:36
Thanks for the work on the missing type definitions. The [imperative API](https://github.com/drcmda/react-spring/blob/master/API-OVERVIEW.md#imperative-api) still seems to be missing types.

**Comment by will-stone** [comment] 2018-07-04 10:44
I presume this is related to this ticket, TSLint is giving me this error for Transition and Spring components:

```
[ts] JSX element type 'Transition' does not have any construct or call signatures.
(alias) class Transition<S extends object, DS extends object>
import Transition
```

**Comment by will-stone** [comment] 2018-07-04 10:56
Scratch that. All I had to do was upgrade the React and ReactDOM types to

```
"@types/react": "^16.4.6",
"@types/react-dom": "^16.0.6",
```

**Comment by mbeauchamp7** [comment] 2018-07-09 15:16
Hi, I was trying to reproduce an example with typescript and realized there are missing typings for the `Keyframes`.
![image](https://user-images.githubusercontent.com/15185355/42459394-8ba72c92-8369-11e8-98b8-20f874141907.png)

**Comment by drcmda** [comment] 2018-07-11 08:45
@mbeauchamp7 looks like it's an old definition. Do you know your way around TS? I welcome PR's.

They're 4 statics, ´script´ is already gone.

https://github.com/drcmda/react-spring/blob/master/src/Keyframes.js

**Comment by mbeauchamp7** [comment] 2018-07-11 21:32
@drcmda I'm not very good with definition files but I can give it a try!

**Comment by drcmda** [comment] 2018-07-12 10:53
Someone just updated typing, i'll try to get some more fixes in and will release soon.

**Comment by lasseborly** [comment] 2018-07-20 13:53
Very cool @drcmda !

Full typings would be so cool. I still get weird errors on Transition though.. Which does seem to have typings?

```
        <Transition
          from={{ opacity: 0 }}
          enter={{ opacity: 1 }}
          leave={{ opacity: 0 }}
        >
          {this.state.loaded && <Welcome>Hello world</Welcome>}
        </Transition>
```

```
 Type '{ children: boolean | Element; from: { opacity: number; }; enter: { opacity: number; }; leave: { ...' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Transition<{}, { opacity: number; }>> & Readonly<...'.
  Type '{ children: boolean | Element; from: { opacity: number; }; enter: { opacity: number; }; leave: { ...' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Transition<{}, { opacity: number; }>> & Readonly<{...'.
    Type '{ children: boolean | Element; from: { opacity: number; }; enter: { opacity: number; }; leave: { ...' is not assignable to type 'Readonly<TransitionProps<{}, { opacity: number; }>>'.
      Types of property 'children' are incompatible.
        Type 'boolean | Element' is not assignable to type 'SpringRendererFunc<{}, { opacity: number; }> | SpringRendererFunc<{}, { opacity: number; }>[] | u...'.
          Type 'true' is not assignable to type 'SpringRendererFunc<{}, { opacity: number; }> | SpringRendererFunc<{}, { opacity: number; }>[] | u...'.
```

**Comment by mbeauchamp7** [comment] 2018-07-20 14:34
@lasseborly I think they have been update, but not released on npm

**Comment by drcmda** [comment] 2018-07-20 19:14
Right, i just updated ...

**Comment by lasseborly** [comment] 2018-07-20 22:22
Ok.. I think I have managed to track my problem down. Limited experience with both react-spring and Typescript might make me come across as ignorant. But here we go.

If I try to go by the docs and make use of `Transition` as described I run into some problems.

```javascript
  <Transition
    from={{ opacity: 0 }}
    enter={{ opacity: 1 }}
    leave={{ opacity: 0 }}
  >
    {loaded && Welcome}
  </Transition>
```

Usage like that resolves in an error: `TypeError: Cannot add property props, object is not extensible`. Looking at the proptypes then and at other code makes it so children and render only takes a function or an array of functions.
So doing that works fine:

```javascript
  <Transition
    from={{ opacity: 0 }}
    enter={{ opacity: 1 }}
    leave={{ opacity: 0 }}
  >
    {loaded &&
      (styles => (
        <Welcome style={styles}>Hello world {styles.opacity}</Welcome>
      ))}
  </Transition>
```

Until we venture into Typescript land where the interface of the `Transition` prop types are exactly like their `prop-types` counterparts. A function or an array of functions.
Which means that it bugs out when it sees `loaded` which is a `boolean`.
Adding `boolean` as part of the `Transition` props interface solves the problem.

If I'm not misunderstanding the problem and I'm not doing something fundamentally wrong you guys can correct me. If not a proposal for a PR I'll gladly produce sounds as follow.

- Rewrite the parts of the documentation that are faulty or misleading.
- Extend the `Transition` interface definition to accept a `boolean`value.
- Extend the `Transition` prop type to accept a `boolean` value. Primarily for parity with the TS interface definition.

Again, I'll gladly put up the PR. Really love this library and would be grateful for the opportunity to contribute. Even if it's "only" typings. 😊

**Comment by drcmda** [comment] 2018-10-26 19:47
Could anyone help fixing types for 6.0? Transition and Trail have changed a little. They accept a single function child: (item, state, index) => props => ReactNode

item is the individual item, transiton and trail are driven by the `items` prop

state can be "enter"|"update"|"leave"

index is the index of the item

http://react-spring.surge.sh/transition

Right now the types declare SpringRendererFunc, which is wrong i guess ...

**Comment by borisyordanov** [comment] 2018-11-21 14:59
Has anyone managed to use react-spring with typescript?

I tried doing this:
```
import { config, Transition } from 'react-spring'
const AnimatedRoutes = (props: RouteComponentProps) => (
    <Transition
        config={config.slow}
        keys={props.location.key}
        from={{ transform: 'translateY(100px)', opacity: 0 }}
        enter={{ transform: 'translateY(0px)', opacity: 1 }}
        leave={{ transform: 'translateY(100px)', opacity: 0 }}
    >
        <Switch location={props.location}>
            <Route path="/" exact={true} component={LandingPage} />
            <Route path="/about" component={HowWorks} />
            <Route path="/1" component={Step1} />
            <Route path="/2" component={Step2} />
            <Route path="/3" component={Step3} />
            <Route path="/4" component={Step4} />
            <Route path="/5" component={Step5} />
        </Switch>
    </Transition>
);
class App extends React.Component {
    public render() {
        return (
            <div className="App">
                <ApolloProvider client={client}>
                    <ReduxProvider store={store}>
                        <Router>
                            <Route render={AnimatedRoutes} />
                        </Router>
                    </ReduxProvider>
                </ApolloProvider>
            </div>
        );
    }
}
```

and got this error:

```
(27,6): Type '{ children: Element; config: SpringConfig; from: { transform: string; opacity: number; }; enter: { transform: string; opacity: number; }; leave: { transform: string; opacity: number; }; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Transition<{}, {}, { transform: string; opacity: number; }, { transform: string; opacity: number; }, { transform: string; opacity: number; }, {}>> & Readonly<...> & Readonly<...>) |
(IntrinsicAttributes & ... 2 more ... & Readonly<...>)'.
  Type '{ children: Element; config: SpringConfig; from: { transform: string; opacity: number; }; enter: { transform: string; opacity: number; }; leave: { transform: string; opacity: number; }; }' is not assignable to type 'Readonly<TransitionProps<{}, {}, { transform: string; opacity: number; }, { transform: string; opacity: number; }, { transform: string; opacity: number; }, {}>>'.
    Property 'items' is missing in type '{ children: Element; config: SpringConfig; from: { transform: string; opacity: number; }; enter: { transform: string; opacity: number; }; leave: { transform: string; opacity: number; }; }'.
```

Why is items required? The type definitions seem to be totally off. What am i missing? (i'm using v 6.4.1 or react-slick)

**Comment by pollen8** [comment] 2018-11-22 12:05
`items` is a required `Transition` prop, so add
```
 <Transition
  items={[1]]
```
Also Transition`s child needs to be a function, see the docs http://react-spring.surge.sh/transition

**Comment by fijisoo** [comment] 2018-12-26 21:10
bump. 
It's really hard to work with lib when you getting errors even in basic usage. 

![image](https://user-images.githubusercontent.com/16739040/50457347-0dd13880-095b-11e9-9b48-999de417fd86.png)

**Comment by fijisoo** [comment] 2018-12-26 21:16
bump.
It's really hard to work with lib when you getting errors even in basic usage.

![image](https://user-images.githubusercontent.com/16739040/50457452-e75fcd00-095b-11e9-8587-d63cf7948b77.png)

```jsx
export const App = () => {
  return (
    <div className={c.main}>
      import { Spring } from 'react-spring'

      <Spring from={{ opacity: 0 }} to={{ opacity: 1 }}>
        {props => <div style={props}>hello</div>}
      </Spring>
    </div>
  );
};
```

**Comment by vpicone** [comment] 2019-02-01 16:12
Not sure if I should make a new issue but `Trail` and presumably some of the other components that can take any Spring prop should extend SpringProps, not SpringBaseProps.

For example, using the after prop with Trail gives the error `Property 'after' does not exist on type...`

**Comment by canastro** [comment] 2019-03-02 11:37
With the latest version of react-spring (with hooks) and using react-konva: 

```ts
import { useSpring, animated } from 'react-spring/konva';
```

I get the following error:
```ts
 TS7016: Could not find a declaration file for module 'react-spring/konva'. 
'/.../node_modules/react-spring/konva.js' implicitly has an 'any' type.
```

Any tip on how I can fix this?

**Comment by drcmda** [comment] 2019-03-03 16:40
The module exists: https://unpkg.com/react-spring@8.0.10/konva.js

**Closed** 2019-04-15 14:08 UTC
Labels: enhancement, good first issue
