### ISSUE TITLE
react-spring v6 importing parallax not working

### ISSUE THREAD

**Issue by iammarkps** [react-spring/react-spring#278] opened 2018-10-25 18:24 UTC
```
Unexpected identifier

/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/addons.js:1
(function (exports, require, module, __filename, __dirname) { import _extends from '@babel/runtime/helpers/esm/extends';
                                                                     ^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.react-spring/dist/addons (/Users/iammark/Projects/openhouse/.next/server/static/development/pages/index.js:2031:18)
    at __webpack_require__ (/Users/iammark/Projects/openhouse/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.js (/Users/iammark/Projects/openhouse/.next/server/static/development/pages/index.js:1785:82)
    at __webpack_require__ (/Users/iammark/Projects/openhouse/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (/Users/iammark/Projects/openhouse/.next/server/static/development/pages/index.js:1964:18)
    at __webpack_require__ (/Users/iammark/Projects/openhouse/.next/server/static/development/pages/index.js:23:31)
```
When I tried to import parallax from 'react-spring/dist/addons' it's throwing me this error.
This is my import code
```
import { ParallaxLayer } from 'react-spring/dist/addons'
import { Spring } from 'react-spring'
```

**Comment by drcmda** [comment] 2018-10-26 09:50
Seems fine here: https://codesandbox.io/s/vyvl2pwnm0?from-embed

I think it's got something to do with your buildsystem. Like if it cannot find babel. I do not include babel, just declare it as peer-dep. To be sure, can you try: import {.....} from 'react-spring/dist/addons.cjs' ? This would pull in the common js build

**Comment by iammarkps** [comment] 2018-10-26 10:29
I think the problem is with NextJS

**Comment by iammarkps** [comment] 2018-10-26 11:52
The old error is gone but now its throw this error instead.
```
global.requestAnimationFrame is not a function

TypeError: global.requestAnimationFrame is not a function
    at requestFrame (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/web.cjs.js:18:17)
    at Controller.start (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/web.cjs.js:1542:18)
    at Controller.update (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/web.cjs.js:1530:47)
    at new Controller (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/web.cjs.js:1335:10)
    at new Parallax (/Users/iammark/Projects/openhouse/node_modules/react-spring/dist/addons.cjs.js:218:25)
    at processChild (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:2435:14)
    at resolve (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:2401:5)
    at ReactDOMServerRenderer.render (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:2728:22)
    at ReactDOMServerRenderer.read (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:2699:25)
    at renderToString (/Users/iammark/Projects/openhouse/node_modules/react-dom/cjs/react-dom-server.node.development.js:3113:25)
    at renderPage (/Users/iammark/Projects/openhouse/node_modules/next/dist/server/render.js:319:26)
    at Function.getInitialProps (/Users/iammark/Projects/openhouse/.next/server/static/development/pages/_document.js:193:18)
    at _callee$ (/Users/iammark/Projects/openhouse/node_modules/next/dist/lib/utils.js:86:30)
    at tryCatch (/Users/iammark/Projects/openhouse/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/iammark/Projects/openhouse/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/iammark/Projects/openhouse/node_modules/regenerator-runtime/runtime.js:114:21)
```

**Comment by drcmda** [comment] 2018-10-26 12:59
Really weird, could you share your repo somehow? It looks to me as if it doesn't pick up the correct entry point (which for the web is src/targets/web/index.js) -- in there the globals are set. Missing globals is almost certainly a weird entry. Or maybe tree-shaking is messing with it. In my projects i'm using straight webpack, and codesandbox, they all seem fine. It must be something peculiar in the way you fetch this lib.

**Comment by iammarkps** [comment] 2018-10-26 13:01
@drcmda https://github.com/iammarkps/openhouse This is my repo

**Comment by drcmda** [comment] 2018-10-26 13:36
This is so weird, i tried to pluck out everything, just pasting a parallax example into index.js and it worked, the moment i do something else it falls appart. It says it can't find index.js:2429 GET http://localhost:3000/Users/drcmda/dev/openhouse/node_modules/react-spring/dist/addons.js 404 (Not Found)

addons.js is right there node_modules

Then i used the .cjs export, now it complains about global.raf not find, which is insane. Can it maybe be that next is using outdated babel or webpack inside?

@TrySound Do you have any idea what this could be? Did this ever happen anywhere else?

**Comment by iammarkps** [comment] 2018-10-26 13:46
NextJS is using babel 7

**Comment by iammarkps** [comment] 2018-10-26 13:48
@drcmda btw nextjs use file-system routing I think 'http://localhost:3000/Users/drcmda/dev/openhouse/node_modules/react-spring/dist/addons.js' won't work.

**Comment by drcmda** [comment] 2018-10-26 14:20
but that was a standard `import { ... } from 'react-spring/dist/addons'` and the console said 404. Have to admit i'm stumped by this.

**Comment by LekoArts** [comment] 2018-10-31 16:30
I'm also experiencing the same issue with Gatsby:
https://github.com/LekoArts/gatsby-starter-portfolio-cara/pull/8

You also can see the Netlify build there.

**Comment by drcmda** [comment] 2018-10-31 17:43
Could you check if "global" is defined at all? It would be weird if that's not the case in a bundled environment. And if you go:

window.global = { requestAnimationFrame: fn => requestAnimationFrame(fn), cancelAnimationFrame: fn => cancelAnimationFrame(fn) }

Befor the other stuff initializes, does that fix it?

**Comment by LekoArts** [comment] 2018-11-01 11:01
> Could you check if "global" is defined at all? It would be weird if that's not the case in a bundled environment. And if you go:

Doing a `console.log(global)` gave me a result with a bunch of key value pairs in it.

> global = { requestAnimationFrame: fn => requestAnimationFrame(fn), cancelAnimationFrame: fn => cancelAnimationFrame(fn) }

Putting it where? Placing it in my index.jsx file it tells me that `requestAnimationFrame is not defined`.

You can try it yourself with the repo though.

**Comment by LekoArts** [comment] 2018-11-01 17:29
I updated, yeah. But `window` is problematic, too:
https://www.gatsbyjs.org/docs/debugging-html-builds/

I got a "window is not defined" error. It would be best to add this check to react-spring, not to my code:
https://github.com/LekoArts/gatsby-starter-portfolio-cara/blob/update-spring/src/pages/index.jsx#L17-L22

Because then `emotion` complains about forwardProp and other stuff.

**Comment by drcmda** [comment] 2018-11-01 18:37
Could this all be a symptom of these build tools? I haven't touched global.requestAnimationFrame or window.requestAnimationFrame and 5.x uses the same format. Both global/window should be fairly common. I think it would be best if next/gatsby sort this out, i am not sure at this point if there's something i can fix otherwise. I don't require or import Parallax anywhere, they are separate packages with standard esm/cjs exports.

**Comment by drcmda** [comment] 2018-11-02 14:10
Are there any steps i would need to take in order to support SSR? I wasn't aware it would cause problems.

**Comment by pieh** [comment] 2018-11-02 15:50
I don't know specifics of Your library, but for component to be "SSR ready" you would want to access browser specific APIs (i.e. `requestAnimationFrame`) not in component `constructor`, `componentWillMount` or `render` lifecycle methods - `componentDidMount` is good place for that. Or if you can't refactor it to not call them there you would need guards like ``typeof window !== `undefined` `` before using them.

We potentially could create mocks in `gatsby` so calling browser APIs in SSR doesn't throw errors but is no-op, but this might cause weird side effects, so I feel it's better if we don't do that - it's easier to debug something if it crash with error than if it fails silently

**Comment by LekoArts** [comment] 2018-11-02 19:03
Errors out with the same one:

```
  10 | var colorNames = [];
  11 | var requestFrame = global ? function (cb) {
> 12 |   return global.requestAnimationFrame(cb);
     | ^
  13 | } : function () {
  14 |   return null;
  15 | };


  WebpackError: TypeError: global.requestAnimationFrame is not a function

  - web.js:12 ./node_modules/react-spring/dist/web.js.requestFrame
    [lib]/[react-spring]/dist/web.js:12:1

  - web.js:1498 Controller.start
    [lib]/[react-spring]/dist/web.js:1498:1

  - web.js:1486 Controller.update
    [lib]/[react-spring]/dist/web.js:1486:1

  - web.js:1290 new Controller
    [lib]/[react-spring]/dist/web.js:1290:1

  - addons.js:212 new Parallax
    [lib]/[react-spring]/dist/addons.js:212:1

  - bootstrap:18 d
    lib/webpack/bootstrap:18:1
```

**Comment by TrySound** [comment] 2018-11-02 20:02
@drcmda `global` is not defined in browsers. You should always polyfill it. I don't think requestFrame will be called in SSR so just change `global` to `window`.

**Comment by TrySound** [comment] 2018-11-02 20:05
The problem exists because webpack and codesandbox silently polyfill this object but it's still not browser thing, it's not specific object. Rollup doesn't do anything with it out of the box, so the bundle is broken with it.

**Comment by iammarkps** [comment] 2018-11-04 03:59
@drcmda Sorry for not helping you fix this problem, I just got a lot of work at school. BTW Thanks you all for helping me with this

**Comment by Huaoe** [comment] 2018-11-05 09:39
hi,
I workaround the issue upgrading to 6.1.7.beta.1 and modifying web.cjs;js

`
var requestFrame = global ? function (cb) {
  return typeof window != 'undefined' ? window.requestAnimationFrame(cb) : function () {
    return null;
  };
} : function () {
  return null;
};
var cancelFrame = global ? function (cb) {
  return typeof window != 'undefined' ? window.cancelAnimationFrame(cb) : function () {
    return null;
  };
} : function () {
  return null;
};`

**Comment by drcmda** [comment] 2018-11-07 12:20
Should be fixed now.

**Comment by LekoArts** [comment] 2018-11-07 20:31
@drcmda Yeah, works now 👍 Thanks!

**Comment by rainstormza** [comment] 2018-11-17 16:01
@drcmda I think this error still happens in Nextjs.

**Comment by drcmda** [comment] 2018-11-17 17:01
@rainstormza what does it say?

**Comment by rainstormza** [comment] 2018-11-17 17:11
import { Parallax, ParallaxLayer } from "react-spring/dist/addons";

```
/node_modules/react-spring/dist/addons.js:1
(function (exports, require, module, __filename, __dirname) { import _extends from '@babel/runtime/helpers/esm/extends';
                                                                     ^^^^^^^^

SyntaxError: Unexpected identifier
```

@drcmda

**Comment by drcmda** [comment] 2018-11-20 09:09
Hmm, wouldn't know what to do on my end, extends is a plain babel runtime method. If it's missing i think that's due to the build system or target system missing that dependency.

**Comment by stunjiturner** [comment] 2018-11-21 23:13
@rainstormza I am in the nextjs spectrum chat, I have the sample code on https://codesandbox.io/s/n3zx9vykp, It seems from testing if you add the ``` import { Parallax, ParallaxLayer } from 'react-spring/dist/addons';
 ``` to any nextjs app you get the error

**Comment by drcmda** [comment] 2018-11-22 07:47
Which babel version do you run, is this babel latest or still the beta?

**Comment by drcmda** [comment] 2018-11-22 07:50
PS. in this issue people are getting the same problem: https://github.com/gatsbyjs/gatsby/issues/7668

And i think it's been because their SSR engine pinned a beta, which is incompatible with babel@stable.

**Comment by stunjiturner** [comment] 2018-11-22 09:44
Latest

**Comment by stunjiturner** [comment] 2018-11-23 17:45
S Tunji Turner
@sturner
12:43pm
https://unpkg.com/react-spring@6.1.9/dist/addons
3:42pm
Looks like it's publishing import/export syntax, node_modules are not touched by Next.js and are marked as externals, the ZEIT Team responded with this update

**Comment by djinzbojst** [comment] 2018-12-04 15:35
Any updates on this? Experiencing the same issue when trying to deploy my NextJs app with some react-spring Parallax-components.

**Comment by janoist1** [comment] 2018-12-04 19:12
Importing `cjs` fixed for me: `import { Parallax, ParallaxLayer } from 'react-spring/dist/addons.cjs.js'`

**Comment by djinzbojst** [comment] 2018-12-05 08:57
Awesome, thanks! This did the job for me aswell.

**Comment by stunjiturner** [comment] 2018-12-05 15:18
``` export default () => (

  <Parallax pages={3} scrolling={false} horizontal ref={ref => this.parallax = ref}>
    <ParallaxLayer offset={0} speed={0.5}>
      <span onClick={() => this.parallax.scrollTo(1)}>
        Layers can contain anything
      </span>
    </ParallaxLayer>
  </Parallax>
); ```

keeps giving me the following error:
TypeError: undefined is not an object (evaluating '_this.parallax = _ref7')

**Comment by JulianJorgensen** [comment] 2019-01-04 11:51
Still seems to be an issue when using with Next.js

**Comment by benlonsdale** [comment] 2019-01-24 11:16
I think the issue here is importing from `import { ParallaxLayer } from 'react-spring/dist/addons'` which has not been run through a transpiler, where `import { ParallaxLayer } from 'react-spring/dist/addons.cjs.js' has.

When importing from the main module the `package.json` points to the `.cjs`. Whether or not this will work will depend on the environment that you are running the code in.

I was having the same error when trying to run tests on the new hooks module but importing from `import { useSpring } from 'react-spring/hooks.cjs.js';` fixed the issue

**Comment by Powdee** [comment] 2019-01-28 00:17
As the @benlonsdale said. The issue is how we import `{ ParallaxLayer }` from addons's file.
Changed my import to `import { ParallaxLayer } from 'react-spring/addons.cjs.js'` and it fixed the issue.
Using `"react-spring": "^7.2.10"`

**Comment by dohomi** [comment] 2019-04-03 05:38
I am getting a different error on 8.0.19 with NextJS and Parallax:
```
TypeError: Cannot read property 'defaultElement' of undefined
Module../node_modules/react-spring/renderprops-addons.cjs.js
./node_modules/react-spring/renderprops-addons.cjs.js:13
  10 | var React = _interopDefault(require('react'));
  11 | var renderprops = require('react-spring/renderprops');
  12 | 
> 13 | var El = renderprops.Globals.defaultElement;
```
```
import {Parallax, ParallaxLayer} from 'react-spring/renderprops-addons.cjs'
```
Any idea how to solve this?

**Closed** 2019-05-27 14:24 UTC
Labels: bug, react-native

**Comment by cyrus-za** [comment] 2019-06-25 11:22
Getting this error with CRA when running tests. CRA does not use Babel 7 yet. 
This happens regardless of using cjs or not. 

```    
> 4 | import { Parallax, ParallaxLayer } from 'react-spring/dist/addons.cjs'
```

I have a typescript environment, but the file importing this is a normal JS file at the moment (have not migrated everything to ts yet). 
`yarn 1.16.0`
`node 11.14.0`
```json
{
    "react-scripts": "^3.0.1",
    "ts-jest": "^24.0.2",
    "jest": "24.7.1",
    "react-spring": "^8.0.25",
    "typescript": "^3.5.2",
}
```

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "noImplicitAny": false,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src"
  ]
}
```

```js
//setupTest.js
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

```

**Comment by TrySound** [comment] 2019-06-25 11:27
@cyrus-za It does https://github.com/facebook/create-react-app/blob/master/packages/babel-preset-react-app/package.json#L24

**Comment by helenkapatsa** [comment] 2019-07-19 12:56
I caught an error 'Parallax' is not exported from 'react-spring' and the simple solution was to update import string to `import {Parallax, ParallaxLayer} from 'react-spring/renderprops-addons'`.

**Comment by tm1000** [comment] 2019-08-13 17:02
Ref #627
