### ISSUE TITLE
Nextjs Cannot Import Parallax

### ISSUE THREAD

**Issue by giovannibonin** [react-spring/react-spring#627] opened 2019-04-08 19:27 UTC
I've had this issue that others seem to be having when using Nextjs, that I cannot import Parallax. It seems that by changing how renderprops is imported on react-spring/renderprops-addons.cjs.js fixes the issue. I.e:

change to
`var renderprops = require(react-spring/renderprops.cjs');`
from
`var renderprops = require(react-spring/renderprops');`

Would that break something else or is there a reason this hasn't been PR'd yet?

Related: https://github.com/react-spring/react-spring/issues/278

**Comment by klaemo** [comment] 2019-04-10 09:54
It looks like react-spring is using the ESM version of `@babel/runtime` in its output bundle:

```js
var _extends = _interopDefault(require('@babel/runtime/helpers/esm/extends'));
```

nextjs doesn't transpile node_modules so you end up with `import/export` syntax in node.

**Comment by giovannibonin** [comment] 2019-04-11 00:53
Is there no solution to this problem for nextjs?

**Comment by gsambrotta** [comment] 2019-04-12 14:33
You can downgrade to react-spring 7 until it will be fixed

**Closed** 2019-05-27 14:24 UTC
Labels: bug

**Comment by tm1000** [comment] 2019-06-04 00:23
This is still an issue. Why is it closed without reference @aleclarson

**Comment by aleclarson** [comment] 2019-06-04 01:23
Sorry. The `react-spring/renderprops` entry point is deprecated. It won't exist in v9.

In v9, you can do `import { Spring } from 'react-spring'` instead.

The OP was trying to `require` the ESM entry point, which apparently isn't allowed in NextJS. In v8, you can do one of the following: 
```js
import { Spring } from 'react-spring/renderprops'
const { Spring } = require('react-spring/renderprops.cjs')
```

**Comment by tm1000** [comment] 2019-06-04 01:28
@aleclarson how does one import addons in 9 (yes seems to work for spring) as this thread is talking about addons specifically.

**Comment by aleclarson** [comment] 2019-06-04 01:32
The next v9-beta will work like this:
```js
import { Parallax } from '@react-spring/addons'
```
The current v9-beta works just like v8.

**Comment by tm1000** [comment] 2019-06-04 01:36
@aleclarson This is actually still an issue

In 9 (@next)
```const {
	Parallax,
	ParallaxLayer,
} = require('react-spring/renderprops-addons.cjs');
```

fails with `Unexpected token export` because its doing what @klaemo stated earlier

**Comment by tm1000** [comment] 2019-06-04 01:43
I've spent some time confirming this is still infact an issue and should be addressed. 

The compiled renderprops-addons.cjs.js references the wrong (non cjs) renderprops file so you get the un "babelized" version of it, which makes it explode. If you change the require line on line 11 from

`var renderprops = require('react-spring/renderprops');` to `var renderprops = require('react-spring/renderprops.cjs');`

It works in both 8 and 9. However we can't keep this.

**Comment by aleclarson** [comment] 2019-06-04 01:46
It's all working in the next v9-beta, which I'm trying to publish asap.

Anyone who wants v8 to work, please send a PR. Here's a good place to start looking: https://github.com/react-spring/react-spring/blob/f2cfad54f77aad26736c56e4f944c474b8d5cbda/rollup.config.js#L110

I'm keeping this closed since it's an issue with an old version.

**Comment by tm1000** [comment] 2019-06-04 01:47
I tried it in 9 and it fails with the same reasoning when doing

```import { Parallax } from 'react-spring/renderprops-addons'
const { Parallax } = require('react-spring/renderprops-addons.cjs')```

If you mean that it will work once you publish support for 

```import { Parallax } from '@react-spring/addons'```

Then I understand and will wait until it's done :-)

**Comment by aleclarson** [comment] 2019-06-04 01:49
Yes, exactly! Sorry for not being clear before.

**Comment by tm1000** [comment] 2019-06-04 01:49
@aleclarson ok carry on thank you for being so patient! :-D

**Comment by deioo** [comment] 2019-08-13 20:40
This still seem to be an issue regardless of Next.js or spring versions, e.g
https://codesandbox.io/s/hello-world-1xx6c

The error is different, but I believe it's the same issue?

**Comment by tm1000** [comment] 2019-08-13 23:24
@deioo I check this weekly and yes react-spring 9 still does not work with NextJS. I believe when @aleclarson gets closer the build will change and it will start working.

It's effectively the same issue. It's because it's loading the non-transpiled version of react-spring.

**Comment by nandorojo** [comment] 2019-10-11 21:47
Using next `9.0.3` and react-spring `8.0.27` and still getting this issue on **Next.js**.

This is only an issue on next. It does work as intended on a regular project [(code sandbox)](https://codesandbox.io/s/dazzling-euler-yiios). 

Tried importing with each of the following, unsuccessfully: 
```js
const {
	Parallax,
	ParallaxLayer,
} = require('react-spring/renderprops-addons.cjs')
// also tried...
const {
	Parallax,
	ParallaxLayer,
} = require('react-spring/renderprops-addons.cjs.js')
// and this:
import { Parallax, ParallaxLayer } from 'react-spring/renderprops-addons.cjs.js'
import { Parallax, ParallaxLayer } from 'react-spring/renderprops-addons'
```
And I'm getting this error:

(I changed the paths to /path/to)
```javascript
Unexpected token export
/path/to/node_modules/@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js:1
export default function _objectWithoutPropertiesLoose(source, excluded) {
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/path/to/node_modules/react-spring/renderprops.js:7:53)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/path/to/node_modules/react-spring/renderprops-addons.cjs.js:11:19)
```

Thanks for your attention!

**Comment by aleclarson** [comment] 2019-10-12 00:12
@nandorojo Can you try with the [latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404)? Thanks 👍

**Comment by nandorojo** [comment] 2019-10-13 01:56
@aleclarson Thanks so much for the quick response! Really appreciate your time. 

Unfortunately still getting an error. I updated:

**package.json**
```js
  "react-spring": "^9.0.0-canary.808.4.e67bf81",
```

And imported like this:
```js
import { Parallax, ParallaxLayer } from 'react-spring/addons'
```

I'm getting this error in the server logs:
```
TypeError: Cannot read property 'Symbol(AnimatedComponent)' of undefined
    at Object.withAnimated (path/to/node_modules/@react-spring/animated/index.cjs.js:416:83)
    at Object.<anonymous> (path/to/node_modules/@react-spring/addons/index.cjs.js:17:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.@react-spring/addons (path/to/.next/server/static/development/pages/index.js:236:18)
    at __webpack_require__ (path/to/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index/index.tsx (path/to/.next/server/static/development/pages/index.js:107:78)
    at __webpack_require__ (path/to/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (path/to/.next/server/static/development/pages/index.js:224:18)
    at __webpack_require__ (path/to/.next/server/static/development/pages/index.js:23:31)
    at path/to/.next/server/static/development/pages/index.js:91:18
```

And in the browser, I'm seeing this error:

```js
Failed to compile

./node_modules/react-spring/node_modules/@react-spring/addons/index.js
Module not found: Can't resolve 'shared' in '/path/to/node_modules/react-spring/node_modules/@react-spring/addons'
```

I am using typescript with next, could that be related to the issue?

Thanks again.

**Comment by aleclarson** [comment] 2019-10-13 13:34
@nandorojo Try installing without a caret range:
```
npm install react-spring@9.0.0-canary.808.4.e67bf81 --save-exact
```

**Comment by nandorojo** [comment] 2019-10-13 18:24
@aleclarson Updated:
```
 "react-spring": "9.0.0-canary.808.4.e67bf81",
```

Still getting the same error as the previous comment. Let me know if there's anything else you think I should try. Thanks!

**Comment by aleclarson** [comment] 2019-10-13 18:44
Did you try with the `.cjs` export?

```
const { Parallax, ParallaxLayer } = require('react-spring/addons')
```

**Comment by nandorojo** [comment] 2019-10-13 19:11
I did, still same error. Happy to make a git repo. Here you go:

https://github.com/nandorojo/react-spring-next-issue

```
git clone https://github.com/nandorojo/react-spring-next-issue
cd react-spring-next-issue
npm i && npm run dev
```

**Comment by aleclarson** [comment] 2019-10-14 14:55
@nandorojo Fixed in `9.0.0-canary.808.8.4a87fcb`

Example repo [here](https://github.com/aleclarson/repro/tree/react-spring-627).

```ts
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
```

**Comment by nandorojo** [comment] 2019-10-14 16:16
@aleclarson Ah, yes!! Thanks so much, updated my project and it's working.

Really appreciate you taking the time for me.

**Comment by honglish** [comment] 2020-03-30 15:09
This is good, except I have one issue with this, which is that it's wanting the props `scrolling` to be a string, and it doesn't work regardless of what you use

**Comment by honglish** [comment] 2020-03-30 15:09
I just manually hid it by passing the styles, overflowY: 'hidden'

**Comment by mimiqkz** [comment] 2020-03-30 22:53
@honglish I also have the same issue, I am wondering if everything else works fine for you ?

**Comment by bryandandan** [comment] 2020-05-01 09:15
@aleclarson i used the **9.0.0-canary.808.8.4a87fcb** version you suggested to @nandorojo and the suggested import, however I'm getting the following error:
`ModuleNotFoundError: Module not found: Error: Can't resolve '@react-spring/parallax'`

**Comment by djammari** [comment] 2020-05-01 23:24
> @aleclarson i used the **9.0.0-canary.808.8.4a87fcb** version you suggested to @nandorojo and the suggested import, however I'm getting the following error:
> `ModuleNotFoundError: Module not found: Error: Can't resolve '@react-spring/parallax'`

check your dependencies... should be : "@react-spring/parallax": "9.0.0-canary.808.8.4a87fcb",
suspect yours is: "react-spring": "9.0.0-canary.808.8.4a87fcb",

**Comment by franciscaluz** [comment] 2020-06-11 15:50
hi, i added the latest beta version, but also can't seem to be able to add the parallax on Next.js. Any suggestions or news on if this was fixed?

**Comment by mimiqkz** [comment] 2020-07-10 11:07
How is this issue still "Closed" can someone reopen this?

**Comment by benjaminbaldoni** [comment] 2020-09-06 19:55
Same problem happens with react-spring 8.0.27 and also with current react-spring@next version. I was able to solve it transpiling react-spring 8.0.27 using [next-transpile-modules](https://github.com/martpie/next-transpile-modules).

On next.js.config:

```
const withTM = require('next-transpile-modules')(['react-spring'])

module.exports = withTM()
```

and then

```
import { Parallax, ParallaxLayer } from 'react-spring/renderprops-addons'
```

Credits to @Jessidhia  https://github.com/react-spring/react-spring/issues/374#issuecomment-460533248

**Comment by Zain-ul-din** [comment] 2022-08-06 10:49
Simply do `import { Parallax, ParallaxLayer } from 'react-spring'` it's working for me. 
`"react-spring": "^9.5.2"`

**Comment by ibraDev-maqtechs** [comment] 2023-08-13 01:07
This is still not working on "next": "13.4.12", "react-spring": "^9.7.2".
Tried the above code, got an error.
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ParrallexSlider`.`
